server:  
  port: ${CUSTOMER_PORT:3333}

spring:
  zipkin:
    base-url: ${ZIPKIN_URL:http://localhost:9411}
  sleuth:
    traceId128: true
    sampler:
      probability: 1.0
  logging:
    pattern:
      console: "%clr(%d{yyyy-MM-dd HH:mm:ss}){faint} %clr(${LOG_LEVEL_PATTERN:-%5p}) %clr([${springAppName:-},%X{X-B3-TraceId:-},%X{X-B3-SpanId:-},%X{X-Span-Export:-}]){yellow} %clr(${PID:- }){magenta} %clr(---){faint} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n${LOG_EXCEPTION_CONVERSION_WORD:-%wEx}"
    level: "[%X{X-B3-TraceId}/%X{X-B3-SpanId}] %-5p [%t] %C{2} - %m%n"
      org.springframework: WARN
      org.hibernate: WARN

application:
  contact:
    name: Oleksandr Grechanov
    url: https://github.com/agre1981/microservices
    email: agre1981@gmail.com
