version: '3.3'

services:
  # Eureka service
  eureka:
    env_file:
      - .env
    build: ./eureka-service
    ports:
      - "8761:8761"

  # Config server
  config:
    env_file:
      - .env
    build: ./config-server
    ports:
      - "8888:8888"
    depends_on:
      - eureka

  # Account service
  account:
    env_file:
      - .env
    build: ./account-service
    ports:
      - "2222:2222"
      # for debug
      - "5005:5005"
    #command: ["./wait-for-it.sh", "${CONFIG_URL}/health", "--", "echo config-server is up"]
    depends_on:
      - eureka
      - config
      - zipkin

  # Customer service
  customer:
    env_file:
      - .env
    build: ./customer-service
    ports:
      - "3333:3333"
     # for debug
      - "5006:5005"
    depends_on:
      - eureka
      - config
      - zipkin

  # Gateway service
  gateway:
    env_file:
      - .env
    build: ./gateway-service
    ports:
      - "8765:8765"
    depends_on:
      - eureka
      - config
      - account
      - customer
      - zipkin

  #Zipkin service
  zipkin:
    image: openzipkin/zipkin
    container_name: zipkin
    ports:
      # Port used for the Zipkin UI and HTTP Api
      - 9411:9411

