version: '3.3'

services:
  # Eureka service
  eureka:
    env_file:
      - .env
    build: ./eureka-service
    ports:
      - "8761:8761"

  # Config server
  config:
    env_file:
      - .env
    build: ./config-server
    ports:
      - "8888:8888"
    depends_on:
      - eureka

  # Account service
  account:
    env_file:
      - .env
    build: ./account-service
    ports:
      - "2222:2222"
      # for debug
      - "5005:5005"
    #command: ["./wait-for-it.sh", "${CONFIG_URL}/health", "--", "echo config-server is up"]
    depends_on:
      - eureka
      - config

  # Customer service
  customer:
    env_file:
      - .env
    build: ./customer-service
    ports:
      - "3333:3333"
     # for debug
      - "5006:5005"
    depends_on:
      - eureka
      - config

  # Gateway service
  gateway:
    env_file:
      - .env
    build: ./gateway-service
    ports:
      - "8765:8765"
    depends_on:
      - eureka
      - config
      - account
      - customer

  # elastic search for kibana
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.3.0
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      - bootstrap.memory_lock=true
      - cluster.name=springelasticgenie
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - "discovery.type=single-node"
    ulimits:
      memlock:
        soft: -1
        hard: -1

  elastichq:
    image: elastichq/elasticsearch-hq
    ports:
      - "5000:5000"
    links:
      - elasticsearch
    depends_on:
      - elasticsearch

  # Kibana service
  kibana:
    image: docker.elastic.co/kibana/kibana:7.3.0
    depends_on:
      - elasticsearch
    ports:
      - "5601:5601"

  #Zipkin service
  zipkin:
    image: openzipkin/zipkin
    ports:
      # Port used for the Zipkin UI and HTTP Api
      - 9411:9411
    healthcheck:
      test: ["CMD-SHELL", "curl --fail http://zipkin:9411/actuator/health || exit 1"]

