server:  
  port: ${DISCOVERY_PORT:8761}
    
eureka:  
  instance:
    hostname: ${DISCOVERY_HOST:localhost}
  client:
    registerWithEureka: false
    fetchRegistry: false
  server:
    enableSelfPreservation: false  